### ISSUE TITLE
MissingMethodException: Default constructor not found for type 

### ISSUE THREAD

**Issue by ctben** [BatteryAcid/unity-cognito-client#3]
![bad_data_filenotfound](https://user-images.githubusercontent.com/4680213/153840069-88997705-4634-4d2f-b02c-9cefabffa471.png)

When run on machine can work properly but when deploy to ElasticBeanstalk will see this error

**Comment by BatteryAcid** [comment]
The "default constructor not found" error usually means you are missing some SDK dependencies.  Please verify your project has all the required DLLs.

**Comment by ctben** [comment]
My project can work fine on the local machine (in unity) but when deploy to ElasticBeanstalk will not work.
So how can I check DLLs files on the ElasticBeanstalk? Do you have any suggestion?

**Comment by BatteryAcid** [comment]
Are you doing this for a WebGL build?  Because the AWS SDK is not supported.  Let me know as I may have some guidance.

The Unity project should have all the DLLs when you build it for deployment. 
I don't know if this will help, but with some target environments like iOS, you need to add a link.xml file: https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/unity-special.html

**Comment by BatteryAcid** [comment]
Closed - lack of activity.
