### ISSUE TITLE
Unable to resolve existing errors when launching project. 

### ISSUE THREAD

**Issue by db1713** [BatteryAcid/unity-cognito-client#4]
![image](https://user-images.githubusercontent.com/55619265/169638040-b9c42cdd-d6e8-4c3e-83d4-af0c5c54b7c0.png)

I have tried most solutions - reimporting, deleting scripts and adding manually, used correct assemblies with NuGet Manager, all file names are correct. 
Out of the box, this project come's with the attached errors.

**Comment by BatteryAcid** [comment]
I just tested this project with a fresh clone and I don't get these errors.  I think those show up when you don't have the required plugins for those AWS imports.  Check your plugins folder and make sure it has everything that's in the repository.  Are there any other errors above those?  Not sure what's going on here.  Also, what platform are you set to build with or are building on?

**Comment by db1713** [comment]
Hey, so I managed to resolve it after a number of things I do not remember doing, but I don't get those errors anymore.
Thanks.

**Comment by BatteryAcid** [comment]
Ok great! Well make sure to update us if you end up remembering what the issue was - thanks!

**Comment by pihels** [comment]
Hey!

Also had the same problem that was resolved by cloning the project.

However when I copied the dll-s from this project to my own I got the same error. Seems like the problem was that the dll-s were imported a native plugins instead of managed. It was resolved after I imported them using rightclick in editor - > Import New Asset... instead of simply dragging them to Unity. So anyone experiencing this error - check that dll Type is Managed in editor.

![awsdllerror](https://user-images.githubusercontent.com/3604570/189660621-cd4b8d7e-de96-4a96-843f-7c778ec69212.png)
